In [1]:
# Load matches (inspect and undertand raw data format)
import pandas as pd
import numpy as np 
from statsbombpy import sb

matches = sb.matches(competition_id=43, season_id=106)
match_id = int(matches.iloc[0]["match_id"])
events = sb.events(match_id=match_id)

print(events.shape)
print(events.columns.tolist())
events.head()

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(3211, 91)
['bad_behaviour_card', 'ball_receipt_outcome', 'ball_recovery_recovery_failure', 'block_deflection', 'block_offensive', 'carry_end_location', 'clearance_aerial_won', 'clearance_body_part', 'clearance_head', 'clearance_left_foot', 'clearance_right_foot', 'counterpress', 'dribble_nutmeg', 'dribble_outcome', 'duel_outcome', 'duel_type', 'duration', 'foul_committed_advantage', 'foul_committed_card', 'foul_committed_type', 'foul_won_advantage', 'foul_won_defensive', 'goalkeeper_body_part', 'goalkeeper_end_location', 'goalkeeper_outcome', 'goalkeeper_position', 'goalkeeper_technique', 'goalkeeper_type', 'id', 'index', 'injury_stoppage_in_chain', 'interception_outcome', 'location', 'match_id', 'minute', 'off_camera', 'out', 'pass_aerial_won', 'pass_angle', 'pass_assisted_shot_id', 'pass_body_part', 'pass_cross', 'pass_cut_back', 'pass_deflected', 'pass_end_location', 'pass_goal_assist', 'pass_height', 'pass_length', 'pass_miscommunication', 'pass_outcome', 'pass_outswinging', 'pass_recipient', 'pass_recipient_id', 'pass_shot_assist', 'pass_switch', 'pass_technique', 'pass_through_ball', 'pass_type', 'period', 'play_pattern', 'player', 'player_id', 'position', 'possession', 'possession_team', 'possession_team_id', 'related_events', 'second', 'shot_aerial_won', 'shot_body_part', 'shot_deflected', 'shot_end_location', 'shot_first_time', 'shot_freeze_frame', 'shot_key_pass_id', 'shot_one_on_one', 'shot_open_goal', 'shot_outcome', 'shot_statsbomb_xg', 'shot_technique', 'shot_type', 'substitution_outcome', 'substitution_outcome_id', 'substitution_replacement', 'substitution_replacement_id', 'tactics', 'team', 'team_id', 'timestamp', 'type', 'under_pressure']

,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 3412, 'lineup': [{'player': {'id...",Serbia,786,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Switzerland,773,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Switzerland,773,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Serbia,786,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Serbia,786,00:00:00.000,Half Start,NaN

In [2]:
# Investigative exercise for data features
print(events.shape)
print(events.columns.tolist())
events.head()

events["type"].value_counts().head(10)
events[events["type"] == "Carry"].head()

# Learnt from this that CARRIES eixist and that for each carry output we also have CONTEXTUAL 
# feature data such as location of carry, end point of carry, team, player, timestamp and
#  under pressure.

(3211, 91)
['bad_behaviour_card', 'ball_receipt_outcome', 'ball_recovery_recovery_failure', 'block_deflection', 'block_offensive', 'carry_end_location', 'clearance_aerial_won', 'clearance_body_part', 'clearance_head', 'clearance_left_foot', 'clearance_right_foot', 'counterpress', 'dribble_nutmeg', 'dribble_outcome', 'duel_outcome', 'duel_type', 'duration', 'foul_committed_advantage', 'foul_committed_card', 'foul_committed_type', 'foul_won_advantage', 'foul_won_defensive', 'goalkeeper_body_part', 'goalkeeper_end_location', 'goalkeeper_outcome', 'goalkeeper_position', 'goalkeeper_technique', 'goalkeeper_type', 'id', 'index', 'injury_stoppage_in_chain', 'interception_outcome', 'location', 'match_id', 'minute', 'off_camera', 'out', 'pass_aerial_won', 'pass_angle', 'pass_assisted_shot_id', 'pass_body_part', 'pass_cross', 'pass_cut_back', 'pass_deflected', 'pass_end_location', 'pass_goal_assist', 'pass_height', 'pass_length', 'pass_miscommunication', 'pass_outcome', 'pass_outswinging', 'pass_recipient', 'pass_recipient_id', 'pass_shot_assist', 'pass_switch', 'pass_technique', 'pass_through_ball', 'pass_type', 'period', 'play_pattern', 'player', 'player_id', 'position', 'possession', 'possession_team', 'possession_team_id', 'related_events', 'second', 'shot_aerial_won', 'shot_body_part', 'shot_deflected', 'shot_end_location', 'shot_first_time', 'shot_freeze_frame', 'shot_key_pass_id', 'shot_one_on_one', 'shot_open_goal', 'shot_outcome', 'shot_statsbomb_xg', 'shot_technique', 'shot_type', 'substitution_outcome', 'substitution_outcome_id', 'substitution_replacement', 'substitution_replacement_id', 'tactics', 'team', 'team_id', 'timestamp', 'type', 'under_pressure']

,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
1879,NaN,NaN,NaN,NaN,NaN,"[39.7, 45.5]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Switzerland,773,00:00:01.742,Carry,NaN
1880,NaN,NaN,NaN,NaN,NaN,"[42.3, 72.2]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Switzerland,773,00:00:05.137,Carry,NaN
1881,NaN,NaN,NaN,NaN,NaN,"[105.6, 74.4]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Switzerland,773,00:00:13.522,Carry,NaN
1882,NaN,NaN,NaN,NaN,NaN,"[113.6, 12.4]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Switzerland,773,00:00:48.188,Carry,True
1883,NaN,NaN,NaN,NaN,NaN,"[106.0, 17.0]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Switzerland,773,00:00:51.771,Carry,True

In [4]:
# Isolate carries into own data for future feature engineering
carries = events[events["type"] == "Carry"].copy()

carry_cols = [
    "id",
    "match_id",
    "team",
    "player",
    "possession",
    "period",
    "minute",
    "second",
    "timestamp",
    "location",
    "carry_end_location",
    "under_pressure"
]

carries = carries[carry_cols]

print(carries.shape)
carries.head()

# Learnt that location and carry_end_location stored as [x,y] lists. Each carry can be linked to 
# a player, team, possession and time. whilst some can happen under pressure and some carries have
# the same start and end location.

(667, 12)

,id,match_id,team,player,possession,period,minute,second,timestamp,location,carry_end_location,under_pressure
1879,0e5c867f-8c40-4754-bc81-014c8cf88b8d,3857256,Switzerland,Remo Freuler,2,1,0,1,00:00:01.742,"[43.1, 43.7]","[39.7, 45.5]",NaN
1880,a54c6781-c843-40bb-9973-cdef963cb218,3857256,Switzerland,Silvan Widmer,2,1,0,5,00:00:05.137,"[42.3, 72.2]","[42.3, 72.2]",NaN
1881,5992d383-954d-44af-9fb1-4f14899d6407,3857256,Switzerland,Djibril Sow,2,1,0,13,00:00:13.522,"[91.1, 76.4]","[105.6, 74.4]",NaN
1882,90093f2c-b161-4a08-9767-14b17f2ad745,3857256,Switzerland,Djibril Sow,4,1,0,48,00:00:48.188,"[100.3, 4.6]","[113.6, 12.4]",True
1883,e9fad88c-6795-4e10-93f0-edd6db302a68,3857256,Switzerland,Breel-Donald Embolo,4,1,0,51,00:00:51.771,"[106.0, 17.0]","[106.0, 17.0]",True

In [5]:
# First feature-engineering step ( split locations into seperate columns for future engineeering - 
# coordiantes can be their own number, allowing models to work)

carries["start_x"] = carries["location"].str[0]
carries["start_y"] = carries["location"].str[1]
carries["end_x"] = carries["carry_end_location"].str[0]
carries["end_y"] = carries["carry_end_location"].str[1] 

carries[["location", "carry_end_location", "start_x", "start_y", "end_x", "end_y"]].head()
carries[["start_x", "start_y", "end_x", "end_y"]].describe()

# Learnt that avg end_x typically larger than avg start_x meaning more often than not the 
# ball was carried forward.

          start_x     start_y       end_x       end_y
count  667.000000  667.000000  667.000000  667.000000
mean    56.734333   40.002399   59.787256   40.188006
std     27.130263   23.803753   27.879764   23.828328
min      1.500000    1.800000    0.100000    0.900000
25%     37.400000   18.350000   38.950000   17.500000
50%     56.000000   39.100000   58.300000   38.200000
75%     76.950000   61.950000   81.000000   63.400000
max    117.600000   79.100000  119.000000   78.900000

In [6]:
# Carry feature calculations
goal_x = 120
goal_y = 40

carries["carry_length"] = np.sqrt(
    (carries["end_x"] - carries["start_x"]) ** 2 +
    (carries["end_y"] - carries["start_y"]) ** 2
)

carries["start_distance_to_goal"] = np.sqrt(
    (goal_x - carries["start_x"]) ** 2 +
    (goal_y - carries["start_y"]) ** 2
)

carries["end_distance_to_goal"] = np.sqrt(
    (goal_x - carries["end_x"]) ** 2 +
    (goal_y - carries["end_y"]) ** 2
)

carries["distance_gain"] = (
    carries["start_distance_to_goal"] - carries["end_distance_to_goal"]
)

carries[
    [
        "player",
        "start_x",
        "start_y",
        "end_x",
        "end_y",
        "carry_length",
        "start_distance_to_goal",
        "end_distance_to_goal",
        "distance_gain"
    ]
].head()

carries[["carry_length", "start_distance_to_goal", "end_distance_to_goal"]].describe()

carries.sort_values("distance_gain", ascending=False) [
    ["player", "team", "start_x", "start_y", "end_x", "end_y", "carry_length", "distance_gain"]
].head(10)

# Can see now that the TOP distance gain shows very aggressive ball progressing actions, 
# whilst large carry_length don't mean more DANGEROUS actions as distance_gain and general
#  distance_from_goal needs to be considered

,player,team,start_x,start_y,end_x,end_y,carry_length,distance_gain
2482,Granit Xhaka,Switzerland,50.4,15.6,96.0,15.1,45.602741,39.169724
2071,Dušan Tadić,Serbia,55.9,17.3,100.4,14.9,44.564672,36.154699
2174,Djibril Sow,Switzerland,48.0,23.1,82.5,32.3,35.705602,35.674440
2399,Strahinja Pavlović,Serbia,27.1,44.7,65.6,21.6,44.898330,35.591296
1984,Filip Kostić,Serbia,54.3,7.9,109.3,3.7,55.160131,35.278346
2178,Filip Kostić,Serbia,45.4,23.1,80.6,21.7,35.227830,33.047835
2145,Fabian Lukas Schär,Switzerland,28.1,59.4,60.4,60.2,32.309906,30.995223
2002,Breel-Donald Embolo,Switzerland,64.4,19.6,90.9,39.3,33.020297,30.115901
2180,Xherdan Shaqiri,Switzerland,52.8,47.5,83.9,52.6,31.515393,29.381515
2015,Ricardo Iván Rodríguez Araya,Switzerland,89.1,11.8,116.4,27.5,31.492539,28.825525

In [7]:
# Basic Danger flag application (not the model but interpretable features of a carry - 
# ball progression, final third entry, penalty area entry)

carries["progressive_carry"] = carries["distance_gain"] >= 10

carries["entered_final_third"] = (
    (carries["start_x"] < 80) & (carries["end_x"] >= 80)
)

start_in_penalty_area = (
    (carries["start_x"] >= 102) &
    (carries["start_y"] >= 18) &
    (carries["start_y"] <= 62)
)

end_in_penalty_area = (
    (carries["end_x"] >= 102) &
    (carries["end_y"] >= 18) &
    (carries["end_y"] <= 62)
)

carries["entered_penalty_area"] = (~start_in_penalty_area) & end_in_penalty_area

carries[
    [
        "player",
        "team",
        "start_x",
        "start_y",
        "end_x",
        "end_y",
        "distance_gain",
        "progressive_carry",
        "entered_final_third",
        "entered_penalty_area"
    ]
].head(10)


carries[
    ["progressive_carry", "entered_final_third", "entered_penalty_area"]
].mean()

carries.sort_values("distance_gain", ascending = False)[
    [
    "player",
    "team",
    "distance_gain",
    "progressive_carry",
    "entered_final_third",
    "entered_penalty_area"
    ]
].head(15)

# Current thresholds seem suitable with progressive carries being rare and even so with 
# final third and penalty enteries. Now have first descriptive dangerous carry framework.

,player,team,distance_gain,progressive_carry,entered_final_third,entered_penalty_area
2482,Granit Xhaka,Switzerland,39.169724,True,True,False
2071,Dušan Tadić,Serbia,36.154699,True,True,False
2174,Djibril Sow,Switzerland,35.674440,True,True,False
2399,Strahinja Pavlović,Serbia,35.591296,True,False,False
1984,Filip Kostić,Serbia,35.278346,True,True,False
2178,Filip Kostić,Serbia,33.047835,True,True,False
2145,Fabian Lukas Schär,Switzerland,30.995223,True,False,False
2002,Breel-Donald Embolo,Switzerland,30.115901,True,True,False
2180,Xherdan Shaqiri,Switzerland,29.381515,True,True,False
2015,Ricardo Iván Rodríguez Araya,Switzerland,28.825525,True,False,True
1925,Ricardo Iván Rodríguez Araya,Switzerland,28.590089,True,True,False
2043,Granit Xhaka,Switzerland,27.309728,True,True,False
2292,Andrija Živković,Serbia,26.587295,True,False,False
1887,Ruben Vargas,Switzerland,26.024531,True,True,False
1943,Milos Veljkovic,Serbia,25.842776,True,False,False

In [8]:
# Carry to Attacking outcomes - Model(supervised learning) target identifying

shot_possessions = (
    events[events["type"] == "Shot"]["possession"]
    .dropna()
    .unique()
)

carries["possession_ends_in_shot"] = carries["possession"].isin(shot_possessions)

carries[
    [
        "player",
        "team",
        "possession",
        "progressive_carry",
        "entered_final_third",
        "entered_penalty_area",
        "possession_ends_in_shot"
    ]
].head(15)

carries["possession_ends_in_shot"].mean()

carries.groupby("progressive_carry")["possession_ends_in_shot"].mean()

carries.groupby("entered_penalty_area")["possession_ends_in_shot"].mean()

# Can see porgressive carries are correlated to higher shot ending rate than non progressive 
# carries, and entires into the penalty area does lead to much higher rate of shot ending 
# possesion. Now have more solidfied danger flag reasoning.

entered_penalty_area
False    0.174772
True     0.555556
Name: possession_ends_in_shot, dtype: float64

In [ ]:
# Simple Model building - baseline classifier.
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

feature_cols = [
    "carry_length",
    "distance_gain",
    "start_x",
    "start_y",
    "end_x",
    "end_y",
    "progressive_carry",
    "entered_final_third",
    "entered_penalty_area"
]

model_df = carries[feature_cols + ["possession_ends_in_shot"]].copy()

X = model_df[feature_cols]
y = model_df["possession_ends_in_shot"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42 
)

model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

print("Train score:", model.score(X_train, y_train))
print("Test score:", model.score(X_test, y_test))

# Coeffcient check for prediction weighting
pd.Series(model.coef_[0], index = feature_cols).sort_values(ascending = False)

# Used Train-Test split for logistic regression model to better test model on predicting 
# from new data. Allows to test multiple features against a target ("shot ending action"). 
# Model score accuracy shows the model doesnt show any obvious sign of overfitting 
# and the coeffecients allow to see which features affect "shot ending actions" the most.

Train score: 0.8273921200750469
Test score: 0.8059701492537313

entered_penalty_area    0.953608
progressive_carry       0.675684
end_y                   0.021867
distance_gain           0.007149
start_x                 0.005981
end_x                   0.000679
start_y                -0.019160
carry_length           -0.019244
entered_final_third    -0.047592
dtype: float64